car_config:
    car_name: gnss
    car_instruction_topic: gnss_car_instructions 
    sensors:
      - config_key: fcn
        topic: FrontCenterGnss/NavSat
        publish: true
        algorithm: manual_drive
        type: other.gnss
