# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/ImageMarkerArray.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.visualization_msgs import ImageMarker_pb2 as ros_dot_visualization__msgs_dot_ImageMarker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ros/visualization_msgs/ImageMarkerArray.proto\x12\x16ros.visualization_msgs\x1a(ros/visualization_msgs/ImageMarker.proto\"H\n\x10ImageMarkerArray\x12\x34\n\x07markers\x18\x01 \x03(\x0b\x32#.ros.visualization_msgs.ImageMarkerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.visualization_msgs.ImageMarkerArray_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEMARKERARRAY._serialized_start=115
  _IMAGEMARKERARRAY._serialized_end=187
# @@protoc_insertion_point(module_scope)
